// Generated from Transport Canada AC 100-001 Issue 07 (Glossary for Pilots and Air Traffic Services Personnel) on 2025-12-31T04:37:42.687Z
export const PILOT_TERMS = new Set([
  "(acc)",
  "(gps)",
  "(laas), and wide area augmentation system (waas)",
  "(vgsi)",
  "(when rvr is not available, 0.5 sm ground visibility is substituted.)",
  ". . . at pilot's discretion",
  ". . . guard",
  ". . . immediately",
  ". . . now",
  "360 overhead",
  "3ld",
  "a set of aircraft and flight crew requirements needed to support performance-based navigation operations",
  "a/c",
  "a/d",
  "aae",
  "aai",
  "aaim",
  "aas",
  "aat",
  "abas",
  "abbreviated precision approach path indicator",
  "abbreviated visual approach slope indicator",
  "abeam",
  "abm",
  "abn",
  "abort (to)",
  "aborted landing",
  "aborted takeoff",
  "aca",
  "acas",
  "acc",
  "accident",
  "acft",
  "acid",
  "acknowledge",
  "acn",
  "acrobatic flight",
  "acsc",
  "active runway",
  "acts of unlawful interference",
  "ad",
  "adf",
  "adiz",
  "adjusted delay factor",
  "ads",
  "ads-b",
  "ads-c",
  "ads-contract",
  "adt",
  "advanced ultralight aeroplane",
  "advise intentions",
  "advisory airspace",
  "advisory area",
  "aerobatic manoeuvre",
  "aerodrome advisory service",
  "aerodrome beacon",
  "aerodrome control service",
  "aerodrome controller",
  "aerodrome elevation",
  "aerodrome geometric centre",
  "aerodrome geometric centre coordinates",
  "aerodrome operator",
  "aerodrome reference point",
  "aerodrome routine meteorological report",
  "aerodrome special meteorological report",
  "aerodrome traffic circuit",
  "aerodrome traffic frequency",
  "aeronautical beacon",
  "aeronautical chart",
  "aeronautical fixed service",
  "aeronautical fixed telecommunications network",
  "aeronautical information circular",
  "aeronautical information manual",
  "aeronautical information publication",
  "aeronautical information regulation and control",
  "aeronautical information service",
  "aeronautical mobile service",
  "aeronautical station",
  "aeroplane",
  "affirm",
  "affirmative",
  "afil",
  "afs",
  "afterimage",
  "aftn",
  "agc",
  "agcc",
  "agl",
  "aic",
  "aid",
  "aidc",
  "aim",
  "aip",
  "aip canada (icao)",
  "air defence identification zone",
  "air defence long-range radar",
  "air defense identification zone",
  "air evacuation",
  "air refuelling",
  "air refuelling control point",
  "air refuelling initial point",
  "air report",
  "air route",
  "air route surveillance radar",
  "air route traffic control center",
  "air show",
  "air sovereignty test",
  "air taxi",
  "air traffic advisory service",
  "air traffic clearance",
  "air traffic control clearance",
  "air traffic control instruction",
  "air traffic control operations support specialist",
  "air traffic control service",
  "air traffic control specialist",
  "air traffic controller",
  "air traffic flow management",
  "air traffic management",
  "air traffic service",
  "air-taxiing",
  "airac",
  "airac canada",
  "airborne collision avoidance system",
  "airborne warning and control system",
  "aircraft",
  "aircraft (rpa)",
  "aircraft accident",
  "aircraft approach category",
  "aircraft arresting cable",
  "aircraft arresting gear",
  "aircraft arresting hook",
  "aircraft arresting system",
  "aircraft autonomous integrity monitoring",
  "aircraft call sign",
  "aircraft captain",
  "aircraft classification number",
  "aircraft commander",
  "aircraft emergency",
  "aircraft identification",
  "aircraft incident",
  "aircraft load rating",
  "aircraft movement",
  "aircraft movement information service",
  "aircraft movement surface condition report",
  "aircraft operator",
  "aircraft parachute system",
  "aircraft radio control of aerodrome lighting",
  "aircraft stand",
  "aircraft stand taxilane",
  "aircraft type designator",
  "aircraft-based augmentation system",
  "airep",
  "airfl",
  "airmet",
  "airmet information",
  "airport",
  "airport advisory area",
  "airport control",
  "airport control service",
  "airport controller",
  "airport elevation",
  "airport information desk",
  "airport operator",
  "airport radar service area",
  "airport reservation office",
  "airport taxi chart",
  "airport traffic area",
  "airship",
  "airside",
  "airspace classification",
  "airspace structure",
  "airspeed",
  "airstart",
  "airway",
  "airway beacon",
  "ais",
  "alerfa",
  "alert notice",
  "alert phase",
  "alerting service",
  "alnot",
  "alr",
  "alrs",
  "alt",
  "alternate aerodrome",
  "altimeter setting",
  "altimeter setting region",
  "altitude",
  "altitude above ground level",
  "altitude above sea level",
  "altitude readout value",
  "altitude reservation",
  "altitude reservation service",
  "altitude reservation specialist",
  "altitude restriction",
  "altrv",
  "ama",
  "amis",
  "amis section",
  "ams",
  "amscr",
  "an airspace of defined dimensions",
  "an electronic navigational system by which hyperbolic lines of position are determined by measuring",
  "and runway guard lights (rgl)",
  "and vertical navigation (vnav)",
  "and visual line of sight (vlos)",
  "aor",
  "apapi",
  "app",
  "approach clearance",
  "approach control facility",
  "approach control service",
  "approach gate",
  "approach mode",
  "approach procedure with vertical guidance",
  "approach sequence",
  "approach speed",
  "approach unicom",
  "approach waypoint (mawp), and downwind termination waypoint (dtw)",
  "approach with vertical guidance",
  "approval request",
  "approved",
  "apreq",
  "apron",
  "apron advisory",
  "apron control",
  "apron management service",
  "aprt",
  "apv",
  "arc",
  "arcal",
  "arcp",
  "arctic control area",
  "are",
  "area control centre",
  "area control service",
  "area controller",
  "area minimum altitude",
  "area navigation",
  "area of responsibility",
  "arip",
  "aro",
  "arp",
  "arrival aircraft interval",
  "arrival control",
  "arrival controller",
  "arrival report",
  "arrival time",
  "ars",
  "arsa",
  "arsr",
  "artcc",
  "arts",
  "arw",
  "as the circumstances require, this may be",
  "asde",
  "asl",
  "assigned arrival time",
  "assigned departure time",
  "asynchronous balanced mode",
  "atc clearance",
  "atc clears",
  "atc contingency command post",
  "atc requests",
  "atc service",
  "atc unit",
  "atcaa",
  "atcs",
  "atf",
  "atfm",
  "atis",
  "atm",
  "ats",
  "ats oi",
  "ats operating irregularity",
  "ats surveillance service",
  "au",
  "auto",
  "automated radar terminal systems",
  "automated weather observation system",
  "automatic altitude reporting",
  "automatic dependent surveillance",
  "automatic dependent surveillance - broadcast",
  "automatic dependent surveillance - contract",
  "automatic direction finder",
  "automatic direction-finding equipment",
  "automatic fixed elt",
  "automatic portable elt",
  "automatic radio compass",
  "automatic terminal information service",
  "automatically deployable elt",
  "autorotation",
  "autorotation to touchdown",
  "autorotational landing",
  "autorotative landing",
  "avasi",
  "average arrival interval",
  "aviation routine weather report",
  "aviation special weather report",
  "aviation weather service",
  "awacs",
  "awos",
  "aww",
  "awy",
  "back course sector",
  "backtrack",
  "ballistic parachute system",
  "balloon",
  "baro-vnav",
  "barometric vertical navigation",
  "barometric vnav",
  "base",
  "base leg",
  "basic ultralight aeroplane",
  "bcst",
  "beacon",
  "bearing",
  "bedpost",
  "below minimums",
  "bird hazard",
  "bird strike",
  "blast fence",
  "blind spot",
  "blind transmission",
  "blind zone",
  "braking action",
  "braking action report",
  "break",
  "break break",
  "brg",
  "broadcast",
  "broadcast (ads-b)",
  "bvlos",
  "c2 link",
  "ca",
  "cae",
  "canadian aircraft",
  "canadian aviation regulations",
  "canadian runway friction index",
  "cancel my ifr flight plan",
  "cancelling ifr",
  "cap",
  "carf",
  "cars",
  "cat",
  "cautionary",
  "cavok",
  "cda",
  "cdfa",
  "ceiling",
  "center weather advisory",
  "central altitude reservation function",
  "central flow control function",
  "centreline fix",
  "cfa",
  "cfcf",
  "cfit",
  "cfs",
  "ch",
  "chaff burst",
  "change-over point",
  "channel",
  "charted visual approach",
  "charted visual flight procedure approach",
  "chase",
  "chase aircraft",
  "chop",
  "circle-to-land maneuver",
  "circling approach",
  "circling approach procedure",
  "circling maneuver",
  "circling manoeuvre",
  "circling minimums",
  "circling procedure",
  "circuit",
  "cirvis",
  "cla",
  "class a, b, c, d, e, f or g airspace",
  "cld",
  "clearance",
  "clearance acknowledgement",
  "clearance limit",
  "clearance readback (cda), and pre-departure clearance (pdc)",
  "clearance request (rcd), and pre-departure clearance (pdc)",
  "cleared as filed",
  "cleared for takeoff",
  "cleared for the option",
  "cleared through",
  "cleared to land",
  "cleared via flight-planned route",
  "climb over the airport (vcoa)",
  "climbout",
  "closed runway",
  "cloud forecast, or area forecast concerning weather phenomena which are of operational interest",
  "cmnps",
  "cmnps transition area",
  "cmnpsa",
  "cns",
  "co-pilot",
  "coastal fix",
  "cockpit voice recorder",
  "command and control link",
  "common frequency area",
  "common point",
  "communications/navigation/surveillance",
  "community aerodrome radio station",
  "company frequency",
  "compass rose",
  "composite flight plan",
  "composite route system",
  "composite separation",
  "compulsory reporting point",
  "conflict",
  "conflict alert",
  "conflict detection",
  "conflict resolution",
  "conflict search",
  "constant descent final approach",
  "contact",
  "contact approach",
  "contact point",
  "continuous descent final approach",
  "contract (ads-c or ads-contract)",
  "control area",
  "control area extension",
  "control sector",
  "control station",
  "control tower",
  "control zone",
  "controlled aerodrome",
  "controlled airspace",
  "controlled flight into terrain",
  "controlled vfr flight",
  "controller",
  "controller-pilot data link communications",
  "controlling agency",
  "convective sigmet",
  "converging runway display aid",
  "coordinated universal time",
  "coordinates",
  "coordinating controller",
  "cop",
  "correction",
  "cpdlc",
  "crash locator beacon",
  "crda",
  "crew member",
  "crfi",
  "crfi reading",
  "critical engine",
  "cross-country flight",
  "cross-polar route",
  "crossing tracks",
  "crosswind component",
  "crosswind leg",
  "cruise climb",
  "cruising altitude",
  "cta",
  "ctr",
  "cva",
  "cvfp",
  "cvfr flight",
  "cvr",
  "cwa",
  "cwas",
  "cz",
  "d-atis",
  "d-volmet",
  "da",
  "danger area",
  "data link atis",
  "data link departure clearance",
  "data link initiation capability",
  "date-time group",
  "day",
  "daylight",
  "dcl",
  "dcpc",
  "dead reckoning navigation",
  "decision altitude",
  "decision height",
  "deform under the weight of an aircraft",
  "department of national defence",
  "departure clearance",
  "departure clearance message",
  "departure clearance readback",
  "departure clearance request",
  "departure control",
  "departure controller",
  "departure time",
  "designated unit",
  "destination alternate aerodrome",
  "destination unit",
  "detresfa",
  "deviation",
  "df",
  "df approach procedure",
  "df fix",
  "df station",
  "df steer",
  "dh",
  "dial-up rco",
  "dial-up remote communications outlet",
  "direct",
  "direct flight",
  "direction-finding station",
  "discrete code",
  "discrete frequency",
  "discrete ssr code",
  "displaced threshold",
  "disregard",
  "distance of turn anticipation",
  "distress phase",
  "dive brake",
  "dlic",
  "dme",
  "dme fix",
  "dme separation",
  "dod flip",
  "downwind",
  "downwind leg",
  "downwind termination waypoint",
  "dp",
  "dr",
  "drag chute",
  "drco",
  "dta",
  "dtw",
  "dvfr",
  "eac",
  "eat",
  "ecc",
  "eccm",
  "ecm",
  "edct",
  "eep",
  "eet",
  "efb",
  "efc",
  "effective coverage",
  "efvs",
  "electronic counter-countermeasures",
  "electronic countermeasures",
  "electronic flight bag",
  "elt",
  "elt(ad)",
  "elt(af)",
  "elt(ap)",
  "elt(s)",
  "emas",
  "emergency coordination centre",
  "emergency frequency",
  "emergency locator transmitter",
  "emergency operations centre",
  "emergency phase",
  "emergency security control of air traffic plan",
  "en-route alternate aerodrome",
  "en-route clearance",
  "en-route climb performance",
  "end exercise point",
  "engineered material arresting system",
  "enhanced flight vision system",
  "enhanced vision system",
  "entry fix",
  "eobt",
  "escat plan",
  "established holding area",
  "estimate",
  "estimated departure time",
  "estimated elapsed time",
  "estimated landing time",
  "estimated off-block time",
  "estimated time en route",
  "estimated time of arrival",
  "estimated time of departure",
  "estimated time of landing",
  "estimating",
  "estimating arrival",
  "eta",
  "etd",
  "ete",
  "etl",
  "evs",
  "ewh",
  "execute missed approach",
  "exercise route",
  "exit fix",
  "expected approach clearance time",
  "expected approach time",
  "expected departure clearance time",
  "expected further clearance time",
  "expedite (to)",
  "eye-to-wheel height",
  "f/o",
  "faa",
  "facf",
  "faf",
  "faker target",
  "fan marker",
  "fan marker beacon",
  "fans",
  "fap",
  "fars",
  "fas",
  "fato",
  "fawp",
  "fdr",
  "feathered propeller",
  "federal aviation administration",
  "federal aviation regulations",
  "feeder fix",
  "feeder route",
  "ferry flight",
  "fi",
  "fic",
  "field elevation",
  "final",
  "final approach",
  "final approach and takeoff area",
  "final approach area",
  "final approach course",
  "final approach course fix",
  "final approach fix",
  "final approach gate",
  "final approach leg",
  "final approach mode",
  "final approach point",
  "final approach segment",
  "final approach waypoint",
  "final leg",
  "fir",
  "first officer",
  "first pilot",
  "fis",
  "fise",
  "fix",
  "fix tolerance area",
  "fl",
  "flag",
  "flag alarm",
  "flameout",
  "flash blindness",
  "flat break",
  "flight advisory controller",
  "flight advisory message",
  "flight advisory service",
  "flight data recorder",
  "flight information centre",
  "flight information region",
  "flight information service",
  "flight information service en route",
  "flight inspection",
  "flight level",
  "flight line",
  "flight management system",
  "flight path",
  "flight plan office",
  "flight plan unique identifier",
  "flight planning centre",
  "flight service specialist",
  "flight service station",
  "flight services",
  "flight test",
  "flight time",
  "flight visibility",
  "flt pln",
  "fly-away",
  "fly-by waypoint",
  "fly-over waypoint",
  "fm",
  "fms",
  "fmsp for arrival",
  "fmsp for departure",
  "fod",
  "follow-me\" vehicle",
  "forecast",
  "foreign object debris",
  "forest fire area",
  "formation flight",
  "forward-looking wind shear warning system",
  "fp",
  "fpc",
  "fpl",
  "fpui",
  "free area",
  "frequency family",
  "front course sector",
  "fss",
  "fuel dumping",
  "fuel jettisoning",
  "fuel remaining",
  "fuel siphoning",
  "fuel venting",
  "ga",
  "gasa",
  "gate hold procedure",
  "gbas",
  "gca",
  "gca controller",
  "geographic area safe altitude",
  "glare",
  "glide path",
  "glide slope",
  "glider",
  "global orbiting navigation satellite system",
  "global positioning system",
  "glonass",
  "gnss",
  "go ahead",
  "go around",
  "go-around",
  "gp",
  "gps",
  "gpws",
  "ground control",
  "ground controlled approach",
  "ground controller",
  "ground effect",
  "ground proximity warning system",
  "ground return",
  "ground-based augmentation system",
  "ground-taxi",
  "groundside",
  "gs",
  "guard lights (rgl)",
  "guidance (lp), and vertical navigation (vnav)",
  "haa",
  "hal",
  "handoff",
  "hang glider",
  "hat",
  "have numbers",
  "hazardous inflight weather advisory service",
  "hdg",
  "heading",
  "heavier-than-air aircraft",
  "heavy",
  "height above aerodrome",
  "height above landing",
  "height above touchdown",
  "height above touchdown zone",
  "height above touchdown zone elevation",
  "helicopter",
  "helicopter parking position",
  "helicopter stand",
  "helipad",
  "heliport",
  "hf",
  "high frequency",
  "high speed exit",
  "high speed taxiway",
  "high speed turnoff",
  "hijacking",
  "hiro",
  "hiwas",
  "hla",
  "holding area",
  "holding fix",
  "holding pattern",
  "holding point",
  "holding procedure",
  "holding stack",
  "homing",
  "hot spot",
  "hover check",
  "hover taxi",
  "i say again",
  "iaf",
  "iap",
  "ias",
  "iawp",
  "ifr",
  "ifr aircraft",
  "ifr control service",
  "ifr departure procedure",
  "ifr flight",
  "ifr landing minimums",
  "ifr military training route",
  "ifss",
  "ils",
  "ils critical area",
  "ils glide path angle",
  "ils reference datum",
  "im",
  "imc",
  "immediate takeoff",
  "in-flight refuelling",
  "in-flight report",
  "incerfa",
  "indicated airspeed",
  "indicated altitude",
  "indicator (vasi)",
  "indicator (vgsi)",
  "inf",
  "information publication (aip)",
  "information request",
  "information service",
  "initial",
  "initial approach",
  "initial approach fix",
  "initial approach segment",
  "initial approach waypoint",
  "initial climb",
  "initial contact",
  "inland navigation fix",
  "inner marker",
  "inner marker beacon",
  "inreq",
  "instrument approach",
  "instrument approach chart",
  "instrument approach procedure",
  "instrument departure procedure",
  "instrument flight rules",
  "instrument landing system",
  "instrument meteorological conditions",
  "instrument runway",
  "intended runway",
  "intentional fuel venting",
  "intermediate approach",
  "intermediate approach fix",
  "intermediate approach segment",
  "intermediate approach waypoint",
  "intermediate fix",
  "intermediate holding position",
  "intermediate waypoint",
  "international civil aviation organization",
  "international flight service station",
  "interrogator",
  "intersection departure",
  "intxn",
  "ip",
  "ir",
  "itinerant aircraft",
  "iwp",
  "j",
  "james brake index",
  "jbi",
  "jet route",
  "jettisoning of external stores",
  "joint rescue coordination centre",
  "joint use restricted area",
  "jrcc",
  "known aircraft",
  "known traffic",
  "laas",
  "lahso",
  "land-based adiz",
  "land-based air defense identification zone",
  "landing",
  "landing area",
  "landing distance available",
  "landing is not effected and that occurs normally",
  "landing minimums",
  "landing roll",
  "landing run",
  "landing sequence",
  "large",
  "laser attack",
  "last assigned altitude",
  "lateral navigation",
  "lateral navigation/vertical navigation",
  "lateral separation",
  "lda",
  "ldin",
  "lee wave",
  "lee wv",
  "level",
  "lf",
  "light gun",
  "light icing",
  "lighter-than-air aircraft",
  "limited weather information system",
  "ll",
  "lla",
  "llws",
  "llz",
  "lnav",
  "lnav/vnav",
  "loc",
  "local aircraft",
  "local area augmentation system",
  "localizer",
  "localizer performance with vertical guidance",
  "localizer performance without vertical guidance",
  "localizer performance without vertical guidance (lp)",
  "localizer type directional aid",
  "localizer usable distance",
  "location indicator",
  "long radius exit",
  "long range air navigation",
  "loran",
  "loss of separation",
  "lost c2 link",
  "lost command and control link",
  "lost link",
  "lost-link procedure",
  "low altitude alert system",
  "low approach",
  "low frequency",
  "low level autorotation",
  "low level tactical training route",
  "low-visibility operations plan",
  "lp",
  "lpv",
  "lvl",
  "lvo",
  "lvop",
  "lvp",
  "lwis",
  "m",
  "ma",
  "maa",
  "mach number",
  "mach number technique",
  "mahwp",
  "make short approach",
  "mandatory frequency",
  "mandatory frequency area",
  "manoeuvring area",
  "manot",
  "map",
  "mapt",
  "marker",
  "marker beacon",
  "master minimum equipment list",
  "matwp",
  "mawp",
  "maximum authorized altitude",
  "mayday",
  "mbst",
  "mca",
  "mda",
  "mea",
  "mean wind",
  "medevac",
  "mel",
  "metar",
  "meteorological bulletin",
  "meteorological information for aircraft in flight",
  "meteorological office",
  "meteorological report",
  "metering",
  "metering fix",
  "metering time",
  "mf",
  "mf area",
  "mfau",
  "mha",
  "microburst",
  "microwave landing system",
  "middle marker",
  "military flight advisory unit",
  "military operations area",
  "military radar control unit",
  "military terminal control area",
  "military terminal control unit",
  "military training route",
  "minimum crossing altitude",
  "minimum descent altitude",
  "minimum en-route altitude",
  "minimum en-route ifr altitude",
  "minimum equipment list",
  "minimum fuel",
  "minimum holding altitude",
  "minimum ifr altitude",
  "minimum navigation performance specifications",
  "minimum obstacle clearance altitude",
  "minimum safe altitude",
  "minimum safe altitude warning",
  "minimum safe speed",
  "minimum sector altitude",
  "minimum vectoring altitude",
  "missed approach",
  "missed approach holding waypoint",
  "missed approach point",
  "missed approach procedure",
  "missed approach segment",
  "missed approach turning waypoint",
  "missed approach waypoint",
  "missing aircraft notice",
  "mlat",
  "mlat system",
  "mls",
  "mm",
  "mmel",
  "mnps",
  "moa",
  "moca",
  "mode",
  "mode c transponder",
  "mode s transponder",
  "model aircraft",
  "moderate icing",
  "monitor",
  "mountainous region",
  "movement area",
  "mra",
  "mrcu",
  "msa",
  "msaw",
  "msg",
  "msl altitude",
  "mtca",
  "mtcu",
  "mtr",
  "mtw",
  "multilateration",
  "multilateration system",
  "multiple touch-and-gos",
  "mva",
  "nad83",
  "nar",
  "nar system",
  "nas",
  "nat",
  "nat ots",
  "nat region",
  "national airspace system",
  "navaid",
  "navigation change-over point",
  "navigation specification",
  "navigational aid",
  "nca",
  "nda",
  "ndb",
  "negative",
  "night",
  "night vision goggles",
  "night vision imaging system",
  "no gyro approach",
  "no radio",
  "no-compass approach",
  "no-transgression zone",
  "noise abatement procedure",
  "non-ats oi",
  "non-ats operating irregularity",
  "non-directional beacon",
  "non-instrument runway",
  "non-manoeuvring area",
  "non-precision approach procedure",
  "non-precision runway",
  "non-radar route",
  "non-radar separation",
  "non-rvsm aircraft",
  "non-standard formation",
  "nordo",
  "normal operating zone",
  "north american datum 1983",
  "north american route",
  "north american routes system",
  "north atlantic organized track system",
  "north warning system",
  "northern control area",
  "notam",
  "notamj",
  "notice to airmen",
  "noz",
  "ntz",
  "nvg",
  "nvis",
  "nws",
  "obst",
  "obstacle clearance altitude",
  "obstacle clearance height",
  "obstacle clearance limit",
  "obstacle departure procedure",
  "obstacle free zone",
  "obstacle light",
  "obstacle limitation surface",
  "obstruction",
  "obstruction light",
  "oca",
  "ocd",
  "oceanic clearance delivery",
  "oceanic control area",
  "oceanic entry point",
  "oceanic exit point",
  "och",
  "ocl",
  "odals",
  "odp",
  "oep",
  "of forecast",
  "off-route vector",
  "ofz",
  "oi",
  "ols",
  "om",
  "omni facility",
  "omnidirectional approach lighting system",
  "on-course\" indication",
  "operating irregularity",
  "operating position",
  "operations plan (rvop)",
  "operations support specialist",
  "orbit",
  "originating unit",
  "oss",
  "out",
  "outer marker",
  "over",
  "overhead approach",
  "overhead break",
  "overrun",
  "overshoot",
  "pal",
  "pan pan",
  "papi",
  "par",
  "paraglider",
  "parallel offset route",
  "pas",
  "pattern",
  "patwas",
  "pavement classification number",
  "pavement load rating",
  "pbn",
  "pbs",
  "pcl",
  "pcn",
  "pdc",
  "penetration turn",
  "peripheral station",
  "personal locator beacon",
  "pfaf",
  "photo block",
  "pic",
  "pilot briefing",
  "pilot briefing service",
  "pilot weather report",
  "pilot-controlled lighting",
  "pilot-in-command",
  "piloted aircraft (rpa)",
  "pilots' automatic telephone weather answering system",
  "pinsa",
  "pirep",
  "pitch",
  "plr",
  "point of activation",
  "point-in-space approach",
  "polar route",
  "position report",
  "position reporting",
  "positive target control",
  "power-back",
  "powered glider",
  "ppr",
  "pps",
  "practice instrument approach",
  "pre-departure clearance",
  "pre-flight pilot briefing",
  "precise final approach fix",
  "precision approach path indicator",
  "precision approach procedure",
  "precision approach radar",
  "precision controller",
  "precision radar approach",
  "precision runway",
  "precision runway cat i",
  "precision runway cat ii",
  "precision runway cat iii",
  "predictive wind shear alert system",
  "predictive wind shear system",
  "preferential arrival route",
  "preferential departure route",
  "preferred ifr route",
  "present position symbol",
  "prevailing visibility",
  "primary frequency",
  "primary means of communication",
  "primary radar",
  "primary surveillance radar",
  "prior permission required",
  "private advisory station",
  "procedure (iap)",
  "procedure altitude",
  "procedure altitude/height",
  "procedure turn",
  "procedure turn inbound",
  "progress report",
  "prohibited area",
  "psr",
  "pt",
  "ptn",
  "pull up and go around",
  "push-back",
  "pws",
  "quad",
  "quick-donning mask",
  "r",
  "ra",
  "raas",
  "radalt",
  "radar",
  "radar advisory",
  "radar approach",
  "radar contact",
  "radar control service",
  "radar echo",
  "radar environment",
  "radar flight following",
  "radar handoff",
  "radar identification",
  "radar identified",
  "radar monitoring",
  "radar navigational assistance",
  "radar return",
  "radar route",
  "radar separation",
  "radar service",
  "radar service terminated",
  "radar vectoring",
  "radar-controlled airspace",
  "radar-identified aircraft",
  "radial",
  "radio",
  "radio beacon",
  "radio direction-finding station",
  "radio magnetic indicator",
  "raim",
  "ramp",
  "rapid exit taxiway",
  "rapid-exit taxiway indicator lights",
  "rar",
  "rate one turn",
  "rate one-half turn",
  "rated coverage",
  "rcag",
  "rcd",
  "rcl",
  "rcll",
  "rco",
  "reactive wind shear system",
  "read back",
  "readback",
  "receiver autonomous integrity monitoring",
  "receiver only",
  "reciprocal tracks",
  "recleared",
  "redl",
  "reduced vertical separation minimum",
  "reduced-visibility operations plan",
  "reil",
  "rejected landing",
  "rejected takeoff",
  "release time",
  "remote aerodrome advisory service",
  "remote communications air/ground facility",
  "remote communications outlet",
  "remote pilot station",
  "remotely piloted aircraft",
  "remotely piloted aircraft system",
  "rendezvous",
  "renl",
  "reporting point",
  "request for clearance",
  "required navigation performance",
  "required navigation performance type",
  "resa",
  "resolution advisory",
  "responsible person",
  "responsible unit",
  "restricted airspace",
  "restricted area",
  "restricted instrument procedure",
  "resume normal navigation",
  "resume normal speed",
  "resume own navigation",
  "retil",
  "rgl",
  "rils",
  "rip",
  "rlls",
  "rmi",
  "rnav",
  "rnav approach",
  "rnav sid",
  "rnav specification",
  "rnav star",
  "rnp",
  "rnp apch",
  "rnp approach",
  "rnp specification",
  "rnpc airspace",
  "road-holding position marking",
  "rocket",
  "roger",
  "rolling takeoff",
  "rollout rvr",
  "ronly",
  "rotation point",
  "rotorcraft",
  "route description",
  "route segment",
  "rpa",
  "rpas",
  "rpas incursion",
  "rps",
  "rsc report",
  "rsc/crfi notam",
  "rsc/jbi notam",
  "rtil",
  "runway",
  "runway acceptance rate",
  "runway centerline lights",
  "runway centre line lights",
  "runway end identifier lights",
  "runway end safety area",
  "runway gradient",
  "runway heading",
  "runway identification lights",
  "runway lead-in light system",
  "runway side stripe marking",
  "runway surface condition notam",
  "runway visibility value",
  "runway-holding position",
  "runway-holding position marking",
  "runways",
  "rvo",
  "rvop",
  "rvr",
  "rvsm",
  "rvsm aircraft",
  "rvv",
  "rws",
  "rwy",
  "safe altitude 100 nm",
  "sail-back",
  "sar",
  "satellite voice communications",
  "satellite-based augmentation system",
  "satvoice",
  "say again",
  "say altitude",
  "sbas",
  "sca",
  "scat i",
  "scia",
  "sda",
  "search and rescue",
  "secondary radar",
  "secondary surveillance radar",
  "sectional chart",
  "sector",
  "see and avoid",
  "selcal",
  "selective calling system",
  "separation",
  "separation minimum",
  "severe icing",
  "severe weather forecast alert",
  "sfo",
  "shf",
  "shock wave",
  "short takeoff and landing aircraft",
  "short-range clearance",
  "show line",
  "shuttle procedure",
  "sid",
  "sidestep maneuver [sic]",
  "sigmet",
  "sigmet information",
  "significant meteorological information",
  "significant point",
  "simulated approach",
  "simulated flameout",
  "simultaneous converging instrument approaches",
  "simultaneous intersecting runway operations",
  "simultaneous operations on parallel or near-parallel instrument runways",
  "siro",
  "site survey",
  "slop",
  "small",
  "soir",
  "southern control area",
  "spade",
  "speci",
  "special aerospace defence exercise",
  "special aviation event",
  "special category i",
  "special emergency",
  "special observations made by aircraft operating on international air routes whenever",
  "special vfr flight",
  "special-use airspace",
  "speed adjustment",
  "sponsor",
  "squawk (to)",
  "squawk ident",
  "ssr",
  "ssr code",
  "ssr mode",
  "stack",
  "standard altimeter setting",
  "standard instrument departure",
  "standard instrument departure chart",
  "standard terminal arrival",
  "standard terminal arrival chart",
  "standby",
  "star",
  "state aircraft",
  "stepdown fix",
  "stol aircraft",
  "stop buzzer",
  "stop squawk",
  "stop-and-go",
  "stopover flight plan",
  "stopway",
  "straight-in approach",
  "strategic lateral offset procedure",
  "sua",
  "suade",
  "super",
  "super high frequency",
  "surface weather observation",
  "surveillance",
  "surveillance - contract (ads-c or ads-contract)",
  "surveillance approach",
  "survival elt",
  "svfr",
  "system (uas), and unmanned air vehicle (uav)",
  "system (uas), and visual line of sight (vlos)",
  "ta",
  "taa",
  "tacan",
  "tactical air navigation system",
  "takeoff",
  "takeoff alternate aerodrome",
  "takeoff time",
  "target",
  "target discrimination",
  "target monitor",
  "tarmac",
  "tas",
  "taws",
  "taxi",
  "taxi chart",
  "taxi to holding point",
  "taxiway",
  "tc",
  "tc aim",
  "tca",
  "tcas",
  "tch",
  "tcu",
  "tdz",
  "tdze",
  "tdzl",
  "telephone information briefing service",
  "temporary flight restriction",
  "terminal area",
  "terminal area entry fix",
  "terminal arrival area",
  "terminal control area",
  "terminal control service",
  "terminal control unit",
  "terminal controller",
  "terminal occupancy value",
  "terminal radar service area",
  "terrain awareness and warning system",
  "terrain awareness warning system",
  "terrain following",
  "test flight",
  "tf",
  "tfr",
  "the area within the canadian domestic airspace (cda) extending upwards from fl 280, underlying",
  "the electromagnetic spectrum. ecms include",
  "the international radiotelephony urgency signal. preferably spoken three times, it indicates a condition",
  "the waypoint designated in the missed approach segment of an instrument approach procedure (iap)",
  "three-letter designator",
  "threshold",
  "threshold crossing height",
  "tibs",
  "tighten your approach",
  "tiltrotor aircraft",
  "time of activation",
  "tlof",
  "tma",
  "tod",
  "top of descent",
  "torching",
  "total eet",
  "total estimated elapsed time",
  "touch-and-go",
  "touchdown",
  "touchdown and lift-off area",
  "touchdown autorotation",
  "touchdown pad",
  "touchdown point",
  "touchdown rvr",
  "touchdown zone",
  "touchdown zone elevation",
  "touchdown zone marking",
  "tov",
  "tower",
  "tower control",
  "tower radar area",
  "tower radar plan",
  "tra",
  "trace icing",
  "track",
  "traffic advisory",
  "traffic alert and collision avoidance system",
  "traffic circuit",
  "traffic in sight",
  "traffic pattern",
  "transborder flight",
  "transcribed weather broadcast",
  "transfer of control",
  "transferring unit",
  "transition",
  "transition altitude",
  "transition area",
  "transition level",
  "transmissometer",
  "transmitting (in the) blind",
  "transponder",
  "transponder airspace",
  "transponder code",
  "transport canada",
  "transport canada aeronautical information manual",
  "transportation safety board of canada",
  "trp",
  "trsa",
  "true airspeed",
  "true mach number",
  "tsb",
  "turbojet aircraft",
  "turboprop aircraft",
  "turbulence",
  "turnoff taxiway",
  "tweb",
  "twr",
  "twy",
  "ua",
  "uas",
  "uav",
  "uhf",
  "ultrahigh frequency",
  "ultralight aeroplane",
  "unable",
  "uncertainty phase",
  "uncontrolled aerodrome",
  "under the hood",
  "under way",
  "unicom",
  "universal",
  "universal communications",
  "unmanned air vehicle",
  "unmanned aircraft",
  "unmanned aircraft system",
  "ups",
  "upwind leg",
  "urgent pirep",
  "user agency",
  "utc",
  "vags",
  "vasi",
  "vcoa",
  "vcs",
  "vdf service",
  "vdp",
  "vector",
  "veer-off",
  "vehicle (uav), and visual line of sight (vlos)",
  "vehicle control service",
  "vehicle corridor",
  "vented fuel",
  "verify your altitude",
  "vertical navigation",
  "vertical navigation (vnav)",
  "vertical separation",
  "vertical takeoff and landing aircraft",
  "vertigo",
  "very high frequency",
  "very low frequency",
  "vfr",
  "vfr aircraft",
  "vfr control service",
  "vfr flight",
  "vfr holding procedure",
  "vfr navigation chart",
  "vfr ott",
  "vfr over-the-top",
  "vfr terminal area chart",
  "vfr-on-top",
  "vgsi",
  "vhf",
  "vhf direction-finding service",
  "vhf omnidirectional range station",
  "vis",
  "visibility",
  "visibility operations (rvo)",
  "visual alignment guidance system",
  "visual approach",
  "visual approach slope indicator",
  "visual climb over airport",
  "visual climb over the airport",
  "visual descent point",
  "visual flight rules",
  "visual glide slope indicator",
  "visual holding",
  "visual line of sight (vlos)",
  "visual meteorological conditions",
  "visual separation",
  "vlf",
  "vlos",
  "vmc",
  "vnav",
  "vnc",
  "volmet",
  "vor receiver test facility",
  "vor station",
  "vortac",
  "vot",
  "vta",
  "vtol aircraft",
  "wa",
  "waas",
  "wac",
  "wafs",
  "wake turbulence",
  "wam",
  "warning area",
  "way-point",
  "waypoint",
  "weather advisory",
  "weather information",
  "wgs-84",
  "whiteout",
  "wide area augmentation system",
  "wide area mlat",
  "wide area multilateration",
  "wilco",
  "wildlife hazard",
  "wildlife strike",
  "wind cone",
  "wind direction indicator",
  "wind shear",
  "wind sleeve",
  "windsock",
  "wing-tip vortex",
  "without vertical guidance (lp), and vertical navigation (vnav)",
  "words twice",
  "world aeronautical chart",
  "world area forecast system",
  "world geodetic system 1984",
  "wp",
  "wpt",
  "ws",
  "z",
  "zone (land-based adiz)",
  "zulu"
]);
